AllCops:
  RunRailsCops: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'config/initializers/*'
    - 'db/**/*'

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 200

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 120

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 20

# Configuration parameters: EnforcedHashRocketStyle, EnforcedColonStyle, EnforcedLastArgumentHashStyle, SupportedLastArgumentHashStyles.
Style/AlignHash:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/AlignParameters:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/SpaceInsideBrackets:
  Enabled: false

Style/SpaceInsideParens:
  Enabled: false
